### ISSUE TITLE
Add registration page

### ISSUE THREAD

**Issue by bakaydmytro** [bakaydmytro/team_seeker_fe#2]
Add a registration page where a user should provide the following information:
- First Name
- Last Name
- Email
- Date of birth
- Password
- Confirm password

or other option to sign up with a Steam account.

In case of successful registration user should be redirected to the user page and the JWT token should be cached.
An error message should be displayed in case there were any errors during registration.

**Comment by NataliaVoloshynska** [comment]
3 SP

**Comment by bakaydmytro** [comment]
@Yatsiuta Oleksandr
