### ISSUE TITLE
Add validation for registration page

### ISSUE THREAD

**Issue by bakaydmytro** [bakaydmytro/team_seeker_fe#3]
First Name:
- Required field.
- Minimum of 2 characters, maximum of 50.
- Only letters  allowed

Last Name:
- Required field.
- Minimum of 2 characters, maximum of 50.
- Only letters are allowed.

Email:
- Required field.
- Must follow a valid email format (e.g., name@example.com).

Age:
- Required field.
- Must be a positive integer.
- Range from 10 to 100

Password:
- Required field.
- Minimum of 8 characters.
- Must include at least one uppercase letter, one lowercase letter, one number, and one special character for security.

Password Confirmation:
- Required field.
- Must exactly match the password field.

**Comment by NataliaVoloshynska** [comment]
2 SP

**Comment by bakaydmytro** [comment]
@Sashlychok
