### ISSUE TITLE
Add validation for login page

### ISSUE THREAD

**Issue by bakaydmytro** [bakaydmytro/team_seeker_fe#4]
Email:
- Required field.
- Must follow a valid email format (e.g., name@example.com).

Password:
Required field.
- Minimum of 8 characters.
- Must include at least one uppercase letter, one lowercase letter, one number, and one special character for security.

**Comment by NataliaVoloshynska** [comment]
2 SP

**Comment by bakaydmytro** [comment]
@Maxim
